Sd tranfo pdf to ig
ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss pull request #2
Opened 2024-07-11 11:41 UTC by sdemeyANS

## Description des changements

* transformation pdf en IG

## Preview

https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig

## A valider

- [x] structuration / menu
- [x] transformation

## Reste à faire

- [x] corrections typo
- [x] corrections hyperliens ou ajout

2024-07-11 11:47 UTC, nriss commented on sushi-config.yaml
> +id: ans.hl7v2.fr.trans.cda.mss
utiliser des tirets plutôt que des points

2024-07-11 11:48 UTC, nriss commented on input/pagecontent/index.md
> +<td width="113">
Il y a une ligne vide dans le tableau

2024-07-11 11:50 UTC, nriss commented on input/pagecontent/cas-usage.md
La qualité des images empêche une lecture aisée

2024-07-11 11:50 UTC, nriss approved these changes

2024-07-16 08:57 UTC, sdemeyANS commented on input/pagecontent/index.md
> +<td width="113">
c'était comme cela dans le pdf page 5 https://esante.gouv.fr/sites/default/files/media_entity/documents/CI_SIS_TRANS_LPS_DOC_CDA_COURRIEL_MSSANTE_V1.1_Post_PAT_2023_CONCERTATION_FINAL.pdf
certainement à supprimer comme sur l'autre volet @isa-ans ?

2024-07-16 09:02 UTC, isa-ans commented on input/pagecontent/index.md
> +<td width="113">
oui bien sûr, à supprimer également sur l'autre volet (erreur typo)

2024-07-24 08:05 UTC, sdemeyANS commented on sushi-config.yaml
> +id: ans.hl7v2.fr.trans.cda.mss
corrigé

2024-07-24 09:53 UTC, isa-ans requested changes

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/index.md
> +Le lecteur pourra également consulter le volet « Transmission de document(s) CDA en HL7v2 » du CI_SIS pour avoir une vision complète et transversale des échanges représentée de façon synthétique sur
Remplacer le terme section 2 par volume 2

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/index.md
> +</div>
Faire apparaître toutes les questions ouvertes ou aucune.

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/index.md
> +<br>
Si possible rétrécir l'image

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +La structure du courriel MDN est décrite en annexe 4 [LIEN].
Insérer ici le lien sur la structure du courriel MDN

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 2 : Réception d’un CR de biologie médicale – Cas nominal</figcaption>
si possible centrer le titre

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 3 : Réception d’un CR de biologie médicale – Gestion des erreurs</figcaption>
si possible centrer le titre

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +La secrétaire médicale du service X de l’établissement-A sélectionne le compte rendu et sélectionne, à partir de l’annuaire de l’établissement, la BAL organisationnelle correspondant au service Y de
pour des questions de lisibilité, passer à la ligne pour débuter ce paragraphe

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +Cette demande d’envoi est traitée par la PFI de l’établissement-A qui réceptionne, analyse les éléments portés par la transaction émise à partir du DPI du service X et construit l’archive IHE_XDM con
ligne 64: passer à la ligne pour débuter ce paragraphe

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +Le courriel envoyé par la BAL attachée à la PFI de l’hôpital-A est réceptionné par la BAL organisationnelle du service Y. Dans le cas d’usage décrit ci-dessous, la secrétaire du service Y de l’établi
passer à la ligne pour débuter ce &

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +Suite au transfert, la PFI de l’établissement-B détecte chaque courriel arrivé sur la BAL applicative du service Y. La PFI de l’hôpital-B extrait les informations du courriel ainsi que la demande d’i
passer à la ligne pour débuter ce &

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +Le DPI intègre le document à partir des informations qu’il reçoit et renvoie un accusé de réception à la PFI.
passer à la ligne pour débuter ce &

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +Dans le contexte du SEGUR vague 2, la PFI doit pouvoir générer un message MDN (Message Disposition Notification) à destination de la BAL organisationnelle du service Y contenant le statut de l’intégr
passer à la ligne pour débuter ce &

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +La structure du message MDN est précisée en annexe 4 [LIEN].
passer à la ligne pour débuter ce & et indiquer le lien sur la structure du courriel MDN

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +Ce cas d’usage nécessite de définir une BAL organisationnelle ainsi qu’une BAL applicative associée pour chaque service clinique de l’établissement B. La PFI ou le DPI peuvent prévoir un paramétrage
Insérer ce & à la note, avec saut de ligne avec ce qui est écrit dans la note

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 4 : Transmission d’un document clinique d’un patient d’un CH vers un autre CH -Cas nominal</figcaption>
si possible, centrer

2024-07-24 09:53 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 5 : Transmission d’un document clinique d’un patient d’un CH vers un autre CH -Gestion des erreurs</figcaption>
centrer si possible

2024-07-24 09:55 UTC, sdemeyANS commented on input/pagecontent/index.md
> +Le lecteur pourra également consulter le volet « Transmission de document(s) CDA en HL7v2 » du CI_SIS pour avoir une vision complète et transversale des échanges représentée de façon synthétique sur
FAIT

2024-07-24 09:55 UTC, sdemeyANS commented on input/pagecontent/index.md
> +<br>
FAIT

2024-07-24 09:58 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 2 : Réception d’un CR de biologie médicale – Cas nominal</figcaption>
FAIT

2024-07-24 09:59 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 4 : Transmission d’un document clinique d’un patient d’un CH vers un autre CH -Cas nominal</figcaption>
FAIT

2024-07-24 09:59 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 5 : Transmission d’un document clinique d’un patient d’un CH vers un autre CH -Gestion des erreurs</figcaption>
FAIT

2024-07-24 10:06 UTC, sdemeyANS commented on input/pagecontent/index.md
> +</div>
c'est ok :)

2024-07-24 10:21 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +La structure du courriel MDN est décrite en annexe 4 [LIEN].
> Insérer ici le lien sur la structure du courriel MDN

courriel ou message d'ailleurs?

2024-07-24 10:36 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +Dans le contexte du SEGUR vague 2, la PFI doit pouvoir générer un message MDN (Message Disposition Notification) à destination de la BAL organisationnelle du service Y contenant le statut de l’intégr
OK

2024-07-24 10:36 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +La structure du message MDN est précisée en annexe 4 [LIEN].
ok

2024-07-24 10:37 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +Ce cas d’usage nécessite de définir une BAL organisationnelle ainsi qu’une BAL applicative associée pour chaque service clinique de l’établissement B. La PFI ou le DPI peuvent prévoir un paramétrage
OK

2024-07-24 13:46 UTC, sdemeyANS commented
A revoir et/ou valider avec @isa-ans 

1. Courriel ou message MDN? => cas d'usage cf commentaire github https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2#discussion_r1689527450
2.  [Organisation métier - Volet Transmission au LPS de documents CDA provenant d'un courriel MSSanté v1.1.0 (ansforge.github.io)](https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/contexte-metier.html) la note (*) s'arrête où?
3.  https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/acteurs-transactions.html#diagramme-des-acteurstransactions manque le sens de la flèche  bleue?
4. [Choix des standards - Volet Transmission au LPS de documents CDA provenant d'un courriel MSSanté v1.1.0 (ansforge.github.io)](https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/standards.html) on modifie ou supprime le dernier point? Les échanges MSSanté doivent prendre en compte les restrictions positionnées sur le message. (Exemple : Un document avec un masquage Médecin ne doit pas être envoyé sur le mail MSSanté du médecin)
5. https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/profils-messages.html#description-du-profil-du-message-mdm décalage ORC dans les tableaux (exemple ORC) est ce important?

2024-07-24 14:35 UTC, isa-ans requested changes

2024-07-24 14:35 UTC, isa-ans commented on input/pagecontent/def-proc-collab.md
> +<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Le CONSOMMATEUR retourne au GESTIONNAIRE un accus&eacute; de r&eacute;ception de la demande de traitement sur le(s) document(s).</p>
Remplacer "Le CONSOMMATEUR retourne au GESTIONNAIRE un accusé de réception de la demande de traitement sur le(s) document(s)" par "Le CONSOMMATEUR retourne au GESTIONNAIRE un accusé de réception de la demande **d'intégration du document.**

2024-07-24 14:35 UTC, isa-ans commented on input/pagecontent/def-proc-collab.md
> +<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Le CONSOMMATEUR retourne au GESTIONNAIRE un accus&eacute; de r&eacute;ception de la demande de suppression de(s) document(s).</p>
Remplacer "Le CONSOMMATEUR retourne au GESTIONNAIRE un accusé de réception de la demande de suppression de(s) document(s)" par "Le CONSOMMATEUR retourne au GESTIONNAIRE un accusé de réception de **suppression du document.**

2024-07-24 14:35 UTC, isa-ans commented on input/pagecontent/standards.md
> +-   Les échanges MSSanté doivent prendre en compte les restrictions positionnées sur le message. (Exemple : Un document avec un masquage Médecin ne doit pas être envoyé sur le mail MSSanté du médecin
cette phrase est à supprimer

2024-07-24 14:35 UTC, isa-ans commented on input/pagecontent/interactions-acteurs.md
> +La gestion de cet accusé de lecture MSSanté (MDN-Message Disposition Notification) va dépendre de l’organisation choisie par l’établissement pour traiter les courriels réceptionnés.
Remplacer "la gestion de cet accusé de lecture..." par "la gestion de l'accusé de lecture..."

2024-07-24 14:35 UTC, isa-ans commented on input/pagecontent/interactions-acteurs.md
> +Dans le cas où le courriel entrant, réceptionné par une BAL organisationnelle, est transféré vers la BAL applicative associée pour traitement automatique de la demande, le message MDN généré par le G
remplacer "message MDN" par "couriel MDN"

2024-07-24 14:35 UTC, isa-ans commented on input/pagecontent/interactions-acteurs.md
> +La structure du message MDN (Message Disposition Notification) est précisée [ici](struct-msg-mdn.html).
remplacer message MDN par courriel MDN

2024-07-24 14:35 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +La structure du courriel MDN est décrite en annexe 4 [LIEN].
courriel

2024-07-24 14:51 UTC, isa-ans requested changes

2024-07-24 14:51 UTC, isa-ans commented on input/pagecontent/cas-usage.md
> +La structure du message MDN est précisée [ici](struct-msg-mdn.html).
remplacer message par courriel MDN

2024-07-25 12:36 UTC, sdemeyANS commented on input/pagecontent/standards.md
> +-   Les échanges MSSanté doivent prendre en compte les restrictions positionnées sur le message. (Exemple : Un document avec un masquage Médecin ne doit pas être envoyé sur le mail MSSanté du médecin
OK

2024-07-25 12:42 UTC, sdemeyANS commented
- [ ] dans profils-messages.html#exemple enlever |||1.2^ CISIS_CDA_HL7_LPS
- [ ] https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/profils-messages.html#document-masqu%C3%A9-aux-professionnels-de-sant%C3%A9 enlevé Cette métadonnée doit obligatoirement prendre la valeur « N » dans le cas où la demande de traitement sur le document est transmise par MSSanté. Dans le cas contraire, la PFI ne doit pas traiter le courriel et doit renvoyer un accusé de lecture MDN (Message Disposition Notification) négatif en direction de l’émetteur. et ajouté ·       Y (Yes) à MASQUE_PS Actif

2024-07-26 09:46 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +La structure du courriel MDN est décrite en annexe 4 [LIEN].
ok voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/31b1a0026fb86a954a9fd7f0c1d174fc079a1959

2024-07-26 09:47 UTC, sdemeyANS commented on input/pagecontent/interactions-acteurs.md
> +Dans le cas où le courriel entrant, réceptionné par une BAL organisationnelle, est transféré vers la BAL applicative associée pour traitement automatique de la demande, le message MDN généré par le G
ok voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/31b1a0026fb86a954a9fd7f0c1d174fc079a1959

2024-07-26 09:47 UTC, sdemeyANS commented on input/pagecontent/interactions-acteurs.md
> +La structure du message MDN (Message Disposition Notification) est précisée [ici](struct-msg-mdn.html).
ok voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/31b1a0026fb86a954a9fd7f0c1d174fc079a1959

2024-07-26 09:47 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +La structure du message MDN est précisée [ici](struct-msg-mdn.html).
ok voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/31b1a0026fb86a954a9fd7f0c1d174fc079a1959

2024-07-26 09:50 UTC, sdemeyANS commented on input/pagecontent/interactions-acteurs.md
> +La gestion de cet accusé de lecture MSSanté (MDN-Message Disposition Notification) va dépendre de l’organisation choisie par l’établissement pour traiter les courriels réceptionnés.
ok voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/ef2ff9406ad6ddb64419bd2e16df5a75871ff9bf

2024-07-26 09:54 UTC, sdemeyANS commented on input/pagecontent/def-proc-collab.md
> +<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Le CONSOMMATEUR retourne au GESTIONNAIRE un accus&eacute; de r&eacute;ception de la demande de suppression de(s) document(s).</p>
ok voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/8407ef12e540b2b2d66cd8f087de0a57099e168f

2024-07-26 09:55 UTC, sdemeyANS commented on input/pagecontent/def-proc-collab.md
> +<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Le CONSOMMATEUR retourne au GESTIONNAIRE un accus&eacute; de r&eacute;ception de la demande de traitement sur le(s) document(s).</p>
ok voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/8407ef12e540b2b2d66cd8f087de0a57099e168f

2024-07-26 09:59 UTC, sdemeyANS commented
>
> 1. Courriel ou message MDN? => cas d'usage cf commentaire github [Sd tranfo pdf to ig #2 (comment)](https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2#discussion_r1689527450)
=>OK https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/31b1a0026fb86a954a9fd7f0c1d174fc079a1959

> 2. [Organisation métier - Volet Transmission au LPS de documents CDA provenant d'un courriel MSSanté v1.1.0 (ansforge.github.io)](https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/contexte-metier.html) la note (*) s'arrête où?
=> OK https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/ef2ff9406ad6ddb64419bd2e16df5a75871ff9bf

> 3. https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/acteurs-transactions.html#diagramme-des-acteurstransactions manque le sens de la flèche  bleue?
=> OK https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/415a9b7fcc5b9372505ffca975695eda20db1564

> 4. [Choix des standards - Volet Transmission au LPS de documents CDA provenant d'un courriel MSSanté v1.1.0 (ansforge.github.io)](https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/standards.html) on modifie ou supprime le dernier point? Les échanges MSSanté doivent prendre en compte les restrictions positionnées sur le message. (Exemple : Un document avec un masquage Médecin ne doit pas être envoyé sur le mail MSSanté du médecin)
=> OK voit commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/ed5a5f2a319a93d8c937f1208998fdbea6406c6c

> 5. https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/profils-messages.html#description-du-profil-du-message-mdm décalage ORC dans les tableaux (exemple ORC) est ce important? 
non Nice to have

2024-07-26 10:01 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +    <figcaption>Figure 3 : Réception d’un CR de biologie médicale – Gestion des erreurs</figcaption>
ok

2024-07-26 10:01 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +Cette demande d’envoi est traitée par la PFI de l’établissement-A qui réceptionne, analyse les éléments portés par la transaction émise à partir du DPI du service X et construit l’archive IHE_XDM con
ok

2024-07-26 10:01 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +Le courriel envoyé par la BAL attachée à la PFI de l’hôpital-A est réceptionné par la BAL organisationnelle du service Y. Dans le cas d’usage décrit ci-dessous, la secrétaire du service Y de l’établi
ok

2024-07-26 10:02 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +Suite au transfert, la PFI de l’établissement-B détecte chaque courriel arrivé sur la BAL applicative du service Y. La PFI de l’hôpital-B extrait les informations du courriel ainsi que la demande d’i
ok

2024-07-26 10:02 UTC, sdemeyANS commented on input/pagecontent/cas-usage.md
> +Le DPI intègre le document à partir des informations qu’il reçoit et renvoie un accusé de réception à la PFI.
ok

2024-07-26 10:22 UTC, sdemeyANS commented
> * [ ]  dans profils-messages.html#exemple enlever |||1.2^ CISIS_CDA_HL7_LPS
FAIT pour info @isa-ans commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/e2ff0a2a84e1de817b2cd8d7d99a472d99f77c59

2024-07-26 10:28 UTC, sdemeyANS commented
> * https://ansforge.github.io/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/sd-tranfo-pdf-to-ig/ig/profils-messages.html#document-masqu%C3%A9-aux-professionnels-de-sant%C3%A9 enlevé Cette métadonnée doit obligatoirement prendre la valeur « N » dans le cas où la demande de traitement sur le document est transmise par MSSanté. Dans le cas contraire, la PFI ne doit pas traiter le courriel et doit renvoyer un accusé de lecture MDN (Message Disposition Notification) négatif en direction de l’émetteur. et ajouté ·       Y (Yes) à MASQUE_PS Actif

fait voir commit https://github.com/ansforge/IG-hl7v2-volet-trans-lps-doc-cda-courriel-mss/pull/2/commits/46df8054d441e8cebebe56e7e1951f3798a26b84 @isa-ans pour info

2024-07-26 15:19 UTC, isa-ans approved these changes
Merci!

2024-07-26 16:05 UTC, merged